from .food_route import FoodResource
from .meal_route import MealResource
from .user_route import UserResource
from .meal_food_route import MealFoodResource
from .category_route import CategoryResource
from .allergy_route import AllergyResource
from .health_issue_route import HealthIssueResource
from .health_reaction_route import HealthReactionResource
from .food_recommendation_route import FoodRecommendationResource